# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: "true"
  branches:
    include:
      - master
      - dev
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml
pr:
  autoCancel: "true"
  branches:
    include:
      - master
      - dev
  paths:
    exclude:
      - README.md
jobs:
- job: Deploy
  variables:
  - ${{ if eq(variables['build.SourceBranchName'], 'dev') }}:
    - group: sfdx-org-dev
    - name: MyVar
      value:  ' `echo "$(Build.SourceVersionMessage)" | head -c 3`'
  - ${{ if eq(variables['build.SourceBranchName'], 'master') }}:
    - group: sfdx-org-master
    - name: MyVar
      value:  ' `echo "$(Build.SourceVersionMessage)" | head -c 3`'
  steps:
    - script: echo $(SalesforceUserName)
    - script: echo $(InstanceUrl)
    - script: echo $(Clientid)
    - script: echo $(Build.SourceVersionMessage)
    - script: echo $(MyVar)
    - script: 
      condition: startsWith(variables['Build.SourceVersionMessage'], 'EC3')


