# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: "true"
  branches:
    include:
      - master
      - dev
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml
jobs:
- job: Deploy
  variables:
  - ${{ if eq(variables['build.SourceBranchName'], 'dev') }}:
    - group: sfdx-org-dev
  - ${{ if eq(variables['build.SourceBranchName'], 'master') }}:
    - group: sfdx-org-master
  steps:
    - script: echo $(SalesforceUserName)
    - script: echo $(InstanceUrl)
    - script: echo $(Clientid)
    - script: echo $(Build.SourceVersionMessage)
    - task: UseNode@1
      displayName: 'Use Node.js 16.13.2'
      inputs:
        version: '16.13.2'
    - bash: 
        npm install sfdx-cli --global
      displayName: Install Salesforce CLI
    - bash: 
        sfdx force:auth:jwt:grant --clientid $(Clientid) --jwtkeyfile ./buildfiles/server.key --username $(SalesforceUserName) --instanceurl $(InstanceUrl) -a prod
      displayName: Authorize salesforce org
    - bash: 
        sfdx force:source:convert -r ./force-app -d ./toDeploy
      displayName: Convert to deploy source
    - bash: 
        sfdx force:mdapi:deploy -l RunLocalTests -c -d ./toDeploy -u prod -w 10
      displayName: Run validation on source code
    - bash: 
        sfdx force:mdapi:deploy -l RunLocalTests -d ./toDeploy -u prod -w 10
      displayName: Deploy source code to Production
